ENVIRONMENT: "RC"
SQL_SCRIPTS_FOLDER: "./resources/sql/"
PIPELINE: false
HEADLESS: false
TIMEOUT: 15000

WEB_CONFIG:
  viewport:
    width: 1920
    height: 1080
  accept_downloads: true
  locale: "pt-BR"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  # Adicione qualquer outra configuração suportada pelo Playwright aqui

# Devices list: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/deviceDescriptorsSource.json
MOBILE_CONFIG:
  viewport:
    width: 360
    height: 640
  device_scale_factor: 2
  is_mobile: true
  has_touch: true
  user_agent: "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.7103.48 Mobile Safari/537.36"
  # Adicione qualquer outra configuração suportada pelo Playwright aqui
