name: Pull Request CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  push_tests:
    permissions: write-all
    name: Pull Request Tests
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=rootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout the test repository
        uses: actions/checkout@v4

      - name: Install Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"

      - name: Create reports folder
        run: |
          mkdir -p reports/allure-report
          mkdir -p reports/allure-results

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install

      - name: Install MySQL Client & Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          python -m pip install --upgrade pip
          pip install mysql-connector-python

      - name: Wait for MySQL and Initialize Database
        run: python init_db.py

      - name: Run the tests
        env:
          DB_NAME: testdb
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: make pipeline

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results
          retention-days: 1

      - name: Post test summary to PR
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            try {
              // Ler apenas o resumo do relatório (não o HTML completo)
              const testOutput = fs.existsSync('reports/report.html')
                ? fs.readFileSync('reports/report.html', 'utf8').match(/<div class="summary">([\s\S]*?)<\/div>/i)?.[1]
                : 'No test report generated';

              const commentBody = `### 🧪 Test Results Summary
              ${testOutput || 'Could not extract test summary'}

              📊 [Download Full HTML Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)`;

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });
            } catch (error) {
              core.warning(`Failed to create comment: ${error}`);
            }
